#!/bin/bash
#Error Percentage and Runtime Calculation Summary, errcalc v1.0
#Copywrite 2014 by Brian Mikolajczyk, brianm12@gmail.com

tr -cd '\11\12\40-\176' < "$1" | grep -v '^GNU' | grep -v '^Press' | grep -v '^Finished' | grep -v 'ipos' | grep -v 'opos' | sed s/'\[A'//g | grep -v '^Copying' | sed '/^$/d' | grep -iv ddrescue > cutfile
tr -cd '\11\12\40-\176' < "$1" | grep -v '^GNU' | grep -v '^Press' | grep -v '^Finished' | grep -v 'ipos' | grep -v 'rescued' | sed s/'\[A'//g | grep -v '^Copying' | sed '/^$/d' | grep -iv ddrescue | awk 'NR % 2 != 0' | grep opos | cut -d\: -f3 | cut -d, -f1 | column -t | sed s/'\ '//g > times
cat cutfile | grep rescued | cut -d\: -f2 | cut -d, -f1 | column -t | sed s/'\ '//g > filesizes
cat cutfile | grep rescued | cut -d\: -f3 | cut -d, -f1 | column -t | sed s/'\ '//g > errorsizes
cat cutfile | grep -v rescued > filelist
paste -d\+ errorsizes filesizes > addition
cat addition | sed s/^/'units\ '/g | sed s/$/'\ \|\ cut\ -d\:\ -f2'/g > mathsadd
chmod +x mathsadd
./mathsadd | sed s/$/\"/g | column -t > fullsizes
paste -d\/ errorsizes fullsizes > division
cat division | sed s/^/'units\ \"100*'/g | sed s/$/'\ \|\ cut\ -d\:\ -f2'/g > mathsdiv
chmod +x mathsdiv
./mathsdiv | sed s/$/\%/g > ratios
paste -d' ' filelist ratios times
rm cutfile filelist errorsizes filesizes division addition ratios mathsadd mathsdiv fullsizes times
